"""add is_public to vocabulary entries

Revision ID: 5417cafafdf8
Revises: 76484f6bf339
Create Date: 2026-05-13 11:54:43.012761

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5417cafafdf8'
down_revision = '76484f6bf339'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vocabulary_entries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_public', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vocabulary_entries', schema=None) as batch_op:
        batch_op.drop_column('is_public')

    # ### end Alembic commands ###
