"""add vocabulary_entries and review_stats tables

Revision ID: 76484f6bf339
Revises: 0aba89128371
Create Date: 2026-05-07 14:06:56.761019

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76484f6bf339'
down_revision = '0aba89128371'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vocabulary_entries',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('lecture', sa.String(length=200), nullable=False),
    sa.Column('date_added', sa.Date(), nullable=False),
    sa.Column('word', sa.String(length=500), nullable=False),
    sa.Column('synonyms', sa.JSON(), nullable=False),
    sa.Column('antonyms', sa.JSON(), nullable=False),
    sa.Column('meaning', sa.Text(), nullable=False),
    sa.Column('translation_en', sa.String(length=500), nullable=False),
    sa.Column('metadata_usage', sa.Text(), nullable=True),
    sa.Column('target_language', sa.String(length=8), nullable=False),
    sa.Column('image_path', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vocabulary_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vocabulary_entries_lecture'), ['lecture'], unique=False)
        batch_op.create_index(batch_op.f('ix_vocabulary_entries_user_id'), ['user_id'], unique=False)

    op.create_table('review_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entry_id', sa.String(length=36), nullable=False),
    sa.Column('times_reviewed', sa.Integer(), nullable=False),
    sa.Column('correct_count', sa.Integer(), nullable=False),
    sa.Column('consecutive_correct', sa.Integer(), nullable=False),
    sa.Column('is_problematic', sa.Boolean(), nullable=False),
    sa.Column('ease_factor', sa.Float(), nullable=False),
    sa.Column('interval_days', sa.Integer(), nullable=False),
    sa.Column('next_review_date', sa.Date(), nullable=True),
    sa.Column('last_reviewed', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['entry_id'], ['vocabulary_entries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entry_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('review_stats')
    with op.batch_alter_table('vocabulary_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vocabulary_entries_user_id'))
        batch_op.drop_index(batch_op.f('ix_vocabulary_entries_lecture'))

    op.drop_table('vocabulary_entries')
    # ### end Alembic commands ###
